version: '3.8'

services:
  s3:
    image: quay.io/minio/minio:RELEASE.2022-06-10T16-59-15Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server ./data --address 0.0.0.0:9000 --console-address ":9001"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3

volumes:
  minio-data: