version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Go version 1, 1.18, 1.17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 1-bullseye
        # Options
        NODE_VERSION: "lts/*"

    # Security Opt and cap_add allow for C++ based debuggers to work. 
    # See `runArgs`: https://github.com/Microsoft/vscode-docs/blob/main/docs/remote/devcontainerjson-reference.md
    # security_opt:
    #   - seccomp:unconfined
    # cap_add:
    #   - SYS_PTRACE

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:s3

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  s3:
    image: quay.io/minio/minio:RELEASE.2022-06-10T16-59-15Z
    restart: always
    # expose is used to not publish port to the host machine, so nginx can be used to forward the port
    expose:
      - 9000
      - 9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server ./data --address 0.0.0.0:9000 --console-address ":9001"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    # network_mode: service:s3 # run nginx in the same network as s3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - s3

volumes:
  minio-data: